subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc
subdir-ccflags-y += -I$(srctree)//drivers/power/supply/mediatek/charger
subdir-ccflags-y += -I$(srctree)/drivers/power/supply/mediatek/misc
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/misc
subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/pubadc_manage

obj-$(CONFIG_AMZN_LD)  += amzn_ld.o
