subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/charger
subdir-ccflags-y += -Werror -I$(srctree)/drivers/power/supply/mediatek/misc
subdir-ccflags-y += -I$(srctree)/drivers/misc/mediatek/typec/tcpc/inc

obj-$(CONFIG_WPC_IDTP922X)  += idtp922x_wireless_power.o
